# Site settings
title: P.L.N
baseurl: "/nguyen/"
url: "https://linh-phuong.github.io"
domain: linh-phuong.github.io

# Author
author:
  name: Phuong Linh Nguyen
  desc: Researcher in Ecology and Evolution
  email: linh.phuong.nguyen@evobio.eu
  selfie: assets/img/profile.png

# social
social:
  email: true
  github: linh-phuong
 
# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
